### ISSUE TITLE
Bug: "No content to display" after Claude completes tasks (SDK compatibility issues in v1.5.0)

### ISSUE THREAD

**Issue by jalen0x** [RichardAtCT/claude-code-telegram#135]
After upgrading to v1.5.0 + Claude Code CLI 2.1.71, bot frequently replies with `(No content to display)` even though Claude completed the task successfully.

**What happens:**
- Send a message → Claude works on it (tools, edits, commands) → finishes OK → but the response is empty
- Progress messages also broken: `StreamUpdate object has no attribute get_tool_names`
- `ConversationEnhancer.update_context()` throws `unexpected keyword argument session_id`

**Repro:** Ask Claude to do something action-heavy (e.g. "update this file"), it does the work but shows no output.

**Root cause:** `StreamUpdate` is missing several methods the handler expects, `update_context()` caller passes wrong args, and when Claude's response is all tool calls with no text, content extraction returns empty string.

Opened PR #136 with fixes.

**Comment by RichardAtCT** [comment]
Fixed by PR #136 which addresses all three reported bugs: (1) adds missing StreamUpdate helper methods (get_tool_names, is_error, etc.), (2) fixes ConversationEnhancer call signature, and (3) generates fallback message when Claude's response is purely tool calls with no text.
